easy_admin:
    site_name: 'AAKB Nyhedslister'

    design:
        menu:
            - { entity: 'Category',  icon: 'search' }
            - { entity: 'Material', icon: 'book' }
            - { entity: 'User', icon: 'user' }

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    list:
        actions: ['show', 'search', 'edit', 'delete']

    entities:
        # List the entity class name you want to manage
        Category:
            class: App\Entity\Category
            list:
                batch_actions:
                    - { label: 'Query Open Search', name: 'query' }
                    - { label: 'Delete', name: 'delete' }
                sort: ['name', 'ASC']
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search' }
                    - { property: 'lastSearchRunAt', label: 'Last run', type: 'datetime' }
                    - { property: 'lastSearchRunSuccess', label: 'Success', type: 'boolean' }
            form:
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search', help: 'Do not include "holdingsitem.accessionDate" ("bad") or "facet.acSource" parameters in the CQL statement. These will be added automatically.' }
                    - 'category'
            show:
                actions:
                    - { label: 'Test search', name: 'query', icon: 'search', css_class: 'btn btn-light' }
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search', help: 'Do not include "holdingsitem.accessionDate" ("bad") or "facet.acSource" parameters in the CQL statement. These will be added automatically.' }
                    - 'category'
                    - { property: 'searchRuns', label: 'Last run', type: 'embedded_list' }
                    - 'createdAt'
                    - 'createdBy'
                    - 'updatedAt'
                    - 'updatedBy'
        SearchRun:
            class: App\Entity\SearchRun
            disabled_actions: ['new', 'edit', 'delete']
            list:
                fields:
                    - runAt
                    - isSuccess
                    - errorMessage
            show:
                fields:
                    - runAt
                    - isSuccess
                    - errorMessage
        Material:
            class: App\Entity\Material
            disabled_actions: ['new', 'edit', 'delete']
            list:
                fields:
                    - titleFull
                    - creatorFiltered
                    - pid
                    - type
                    - date
                    - categories
            show:
                fields:
                    - titleFull
                    - { property: 'creatorFiltered', type: 'string', help: 'The first non null value from "Creator", "CreatorAut", "CreatorCre", "Contributor", "ContributorAct", "ContributorAut", "ContributorCtb", "ContributorDkfig" and "Publisher" in that order' }
                    - { property: 'creator', label: 'Creator', type: 'string' }
                    - { property: 'creatorAut', label: 'CreatorAut', type: 'string' }
                    - { property: 'creatorCre', label: 'CreatorCre', type: 'string' }
                    - { property: 'contributor', label: 'Contributor', type: 'string' }
                    - { property: 'contributorAct', label: 'ContributorAct', type: 'string' }
                    - { property: 'contributorAut', label: 'ContributorAut', type: 'string' }
                    - { property: 'contributorCtb', label: 'ContributorCtb', type: 'string' }
                    - { property: 'contributorDkfig', label: 'ContributorDkfig', type: 'string' }
                    - abstract
                    - type
                    - publisher
                    - pid
                    - date
                    - { property: 'coverUrl', label: 'Cover', type: 'image' }
                    - categories

        User:
            class: App\Entity\User
            role: ROLE_ADMIN
            list:
                sort: ['username', 'ASC']
                fields:
                    - username
                    - email
                    - enabled
                    - roles
            new:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'password', type: 'password', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'password', type: 'password', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            show:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - 'roles'
                    - 'createdAt'
                    - 'createdBy'
                    - 'updatedAt'
                    - 'updatedBy'
