easy_admin:
    site_name: 'AAKB Nyhedslister'

    design:
        menu:
            - { entity: 'Search',  icon: 'search' }
            - { entity: 'Category', icon: 'tag' }
            - { entity: 'Material', icon: 'book' }
            - { entity: 'User', icon: 'user' }

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    list:
        actions: ['show', 'search', 'edit', 'delete']

    entities:
        # List the entity class name you want to manage
        Search:
            class: App\Entity\Search
            list:
                sort: ['name', 'ASC']
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search' }
                    - 'category'
            form:
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search', help: 'Do not include "holdingsitem.accessionDate" ("bad") or "facet.acSource" parameters in the CQL statement. These will be added automatically.' }
                    - 'category'
            show:
                fields:
                    - 'name'
                    - { property: 'cqlSearch', label: 'CQL search', help: 'Do not include "holdingsitem.accessionDate" ("bad") or "facet.acSource" parameters in the CQL statement. These will be added automatically.' }
                    - 'category'
                    - { property: 'searchRuns', label: 'Last run', type: embedded_list }
                    - 'createdAt'
                    - 'createdBy'
                    - 'updatedAt'
                    - 'updatedBy'
        SearchRun:
            class: App\Entity\SearchRun
            disabled_actions: ['new', 'edit', 'delete']
            list:
                fields:
                    - runAt
                    - isSuccess
                    - errorMessage
            show:
                fields:
                    - runAt
                    - isSuccess
                    - errorMessage
        Category:
            class: App\Entity\Category
            list:
                sort: ['name', 'ASC']
                fields:
                    - 'name'
                    - 'searches'
            edit:
              fields:
                - 'name'
                - 'searches'
            new:
              fields:
                - 'name'
                - 'searches'
            show:
                fields:
                    - 'name'
                    - 'searches'
                    - 'createdAt'
                    - 'createdBy'
                    - 'updatedAt'
                    - 'updatedBy'
        Material:
            class: App\Entity\Material
            disabled_actions: ['new', 'edit', 'delete']
            list:
                fields:
                    - title
                    - creator
                    - pid
                    - date
                    - searches
            show:
                fields:
                    - title
                    - creator
                    - abstract
                    - publisher
                    - pid
                    - date
                    - searches

        User:
            class: App\Entity\User
            role: ROLE_ADMIN
            list:
                sort: ['username', 'ASC']
                fields:
                    - username
                    - email
                    - enabled
                    - roles
            new:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'password', type: 'password', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'password', type: 'password', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            show:
                fields:
                    - name
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - 'roles'
                    - 'createdAt'
                    - 'createdBy'
                    - 'updatedAt'
                    - 'updatedBy'
